//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Settings/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""PlayerActions"",
            ""id"": ""687196b5-a7f8-4c7a-a040-1ccb8ec4dd1f"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""c87c0b2d-7995-447e-9307-6262af5cfce4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OneButton"",
                    ""type"": ""Button"",
                    ""id"": ""a59dcc06-0b8d-4c42-92cc-61d15b8f8571"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TwoButton"",
                    ""type"": ""Button"",
                    ""id"": ""41ab75f8-8b58-462e-ab72-8a027198087a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThreeButton"",
                    ""type"": ""Button"",
                    ""id"": ""f117e22d-761b-4301-86fd-60241cad61e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FourButton"",
                    ""type"": ""Button"",
                    ""id"": ""6a6307df-2b23-4943-a8a0-9bf3113c4b03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FiveButton"",
                    ""type"": ""Button"",
                    ""id"": ""550380f4-aa15-4b86-8a44-aebf7d81fbc1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""a5b8f042-084c-4808-ae38-b6957282804e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""372322c1-44f9-4c1e-b32d-fb0e37ad06d8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60e7d8c6-afb1-4428-a56a-0fcb18b326f6"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OneButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2203ff57-917f-4a05-a46a-3f397a1a255d"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TwoButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fb695d1-1d61-4b16-91c5-12908c75d9ae"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThreeButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f016a375-ae77-4ae6-b636-11df46da4b46"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FourButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b058b5f-b907-4b56-b5ee-ea5792533822"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FiveButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f96919d-3e1f-472b-aefe-197e36114469"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerActions
        m_PlayerActions = asset.FindActionMap("PlayerActions", throwIfNotFound: true);
        m_PlayerActions_Select = m_PlayerActions.FindAction("Select", throwIfNotFound: true);
        m_PlayerActions_OneButton = m_PlayerActions.FindAction("OneButton", throwIfNotFound: true);
        m_PlayerActions_TwoButton = m_PlayerActions.FindAction("TwoButton", throwIfNotFound: true);
        m_PlayerActions_ThreeButton = m_PlayerActions.FindAction("ThreeButton", throwIfNotFound: true);
        m_PlayerActions_FourButton = m_PlayerActions.FindAction("FourButton", throwIfNotFound: true);
        m_PlayerActions_FiveButton = m_PlayerActions.FindAction("FiveButton", throwIfNotFound: true);
        m_PlayerActions_Rotate = m_PlayerActions.FindAction("Rotate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerActions
    private readonly InputActionMap m_PlayerActions;
    private IPlayerActionsActions m_PlayerActionsActionsCallbackInterface;
    private readonly InputAction m_PlayerActions_Select;
    private readonly InputAction m_PlayerActions_OneButton;
    private readonly InputAction m_PlayerActions_TwoButton;
    private readonly InputAction m_PlayerActions_ThreeButton;
    private readonly InputAction m_PlayerActions_FourButton;
    private readonly InputAction m_PlayerActions_FiveButton;
    private readonly InputAction m_PlayerActions_Rotate;
    public struct PlayerActionsActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActionsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_PlayerActions_Select;
        public InputAction @OneButton => m_Wrapper.m_PlayerActions_OneButton;
        public InputAction @TwoButton => m_Wrapper.m_PlayerActions_TwoButton;
        public InputAction @ThreeButton => m_Wrapper.m_PlayerActions_ThreeButton;
        public InputAction @FourButton => m_Wrapper.m_PlayerActions_FourButton;
        public InputAction @FiveButton => m_Wrapper.m_PlayerActions_FiveButton;
        public InputAction @Rotate => m_Wrapper.m_PlayerActions_Rotate;
        public InputActionMap Get() { return m_Wrapper.m_PlayerActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActionsActions instance)
        {
            if (m_Wrapper.m_PlayerActionsActionsCallbackInterface != null)
            {
                @Select.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnSelect;
                @OneButton.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnOneButton;
                @OneButton.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnOneButton;
                @OneButton.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnOneButton;
                @TwoButton.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnTwoButton;
                @TwoButton.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnTwoButton;
                @TwoButton.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnTwoButton;
                @ThreeButton.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnThreeButton;
                @ThreeButton.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnThreeButton;
                @ThreeButton.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnThreeButton;
                @FourButton.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnFourButton;
                @FourButton.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnFourButton;
                @FourButton.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnFourButton;
                @FiveButton.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnFiveButton;
                @FiveButton.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnFiveButton;
                @FiveButton.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnFiveButton;
                @Rotate.started -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_PlayerActionsActionsCallbackInterface.OnRotate;
            }
            m_Wrapper.m_PlayerActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @OneButton.started += instance.OnOneButton;
                @OneButton.performed += instance.OnOneButton;
                @OneButton.canceled += instance.OnOneButton;
                @TwoButton.started += instance.OnTwoButton;
                @TwoButton.performed += instance.OnTwoButton;
                @TwoButton.canceled += instance.OnTwoButton;
                @ThreeButton.started += instance.OnThreeButton;
                @ThreeButton.performed += instance.OnThreeButton;
                @ThreeButton.canceled += instance.OnThreeButton;
                @FourButton.started += instance.OnFourButton;
                @FourButton.performed += instance.OnFourButton;
                @FourButton.canceled += instance.OnFourButton;
                @FiveButton.started += instance.OnFiveButton;
                @FiveButton.performed += instance.OnFiveButton;
                @FiveButton.canceled += instance.OnFiveButton;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
            }
        }
    }
    public PlayerActionsActions @PlayerActions => new PlayerActionsActions(this);
    public interface IPlayerActionsActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnOneButton(InputAction.CallbackContext context);
        void OnTwoButton(InputAction.CallbackContext context);
        void OnThreeButton(InputAction.CallbackContext context);
        void OnFourButton(InputAction.CallbackContext context);
        void OnFiveButton(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
    }
}
